version: '3'

services:
  gateway:
    build:
      context: ../
      dockerfile: src/Gateway/Dockerfile
    container_name: ecommerce-gateway
    restart: unless-stopped
    ports:
      - 5001:80
    networks:
      - ecommerce

  discounts-service:
    build:
      context: ../
      dockerfile: src/Services/Discounts/Dockerfile
    container_name: ecommerce-discounts-service
    restart: unless-stopped
    ports:
      - 5010:80
    networks:
      - ecommerce

  orders-service:
    build:
      context: ../
      dockerfile: src/Services/Orders/Dockerfile
    container_name: ecommerce-orders-service
    restart: unless-stopped
    ports:
      - 5020:80
    networks:
      - ecommerce

  products-service:
    build:
      context: ../
      dockerfile: src/Services/Products/Dockerfile
    container_name: ecommerce-products-service
    restart: unless-stopped
    ports:
      - 5030:80
    networks:
      - ecommerce

  returns-service:
    build:
      context: ../
      dockerfile: src/Services/Returns/Dockerfile
    container_name: ecommerce-returns-service
    restart: unless-stopped
    ports:
      - 5040:80
    networks:
      - ecommerce

  reviews-service:
    build:
      context: ../
      dockerfile: src/Services/Reviews/Dockerfile
    container_name: ecommerce-reviews-service
    restart: unless-stopped
    ports:
      - 5050:80
    networks:
      - ecommerce

  users-service:
    build:
      context: ../
      dockerfile: src/Services/Users/Dockerfile
    container_name: ecommerce-users-service
    restart: unless-stopped
    ports:
      - 5060:80
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
    external: true
